---
include:
  - board: nice_nano@2.0.0
    shield: kyria_rev3_left nice_view_adapter nice_view
  - board: nice_nano@2.0.0
    shield: kyria_rev3_right nice_view_adapter nice_view
  - board: nice_nano@2.0.0
    shield: settings_reset
